### ISSUE TITLE
Add new areas to MakeMyIsland.mv website

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#1]
These new areas are: 
- Greater Male' Area (3 islands)
  - Male'
  - Hulhumale'
  - Villimale'
- Fonadhoo Stretch (3 islands)
  - Gan
  - Kadhdhoo
  - Maandhoo

Keeping:
- Fonadhoo (Already covered)

If I recall from the original set up, the boundaries are not the official ones, they're ones we drew. @davewhiteland could confirm though.

**Comment by davea** [comment]
Gan and Maandhoo don't have an obvious boundary line between them. @JenMysoc any idea where this boundary should lie?

**Comment by JenMysoc** [comment]
Hm I think we will need to ask them. My first thought would be on Google where the big yellow road ends. But I don't know for sure!

![screen shot 2015-07-27 at 14 41 02](https://cloud.githubusercontent.com/assets/4170351/8907385/7826cd06-346d-11e5-8c18-e024d8cd374f.png)

**Comment by davea** [comment]
I've added the areas and geometries to [international mapit](http://international.mapit.mysociety.org/areas/ADMIN.html), and they're active on the staging site.

**Comment by dracos** [comment]
Areas on live too.
