### ISSUE TITLE
Create version of FixMyStreet app for the Maldives to link with MakeMyIsland site

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#10]
Changes to be made are:
- [x] Colour scheme to match the makemyisland.mv site (when these have been discussed with Zarino on #13 )
- [x] Logo for the app once Zarino's mockup of #8 has been done
- [x] Create branded splash screens
- [x] Replace images with branded versions (e.g. location screen)

**Comment by JenMysoc** [comment]
Changes to be made are:

- Colour scheme to match the makemyisland.mv site (when these have been discussed with Zarino on #13 )
- Logo for the app once Zarino's mockup of #8 has been done

**Comment by davea** [comment]
The image assets we need for the app:
- Logo for use as app icon in the following pixel sizes:
  - Android:
    - 36x36
    - 48x48
    - 72x72
    - 96x96
  - iOS:
    - 57x57
    - 76x76
    - 114x114
    - 120x120
    - 152x152
- Splash screen in the following pixel sizes:
  - Android:
    - 320x480
    - 640x960
    - 1496x2048
  - iOS:
    - 640x960
    - 640x1136
    - 750x1334
    - 768x1024
    - 1536x2048
- Logo superimposed on radar graphic (i.e. branded version of [this image](https://github.com/mysociety/fixmystreet-mobile/blob/makemyisland-rebrand/www/images/radar.png))
  - 640x640 pixels

**Comment by JenMysoc** [comment]
Great! Thanks @davea ; will @zarino sort out the image assets or should I request these from our partners?

**Comment by zarino** [comment]
@JenMysoc – I have a high-res version of the stacked MakeMyIsland logo. But is that what they want to use for the app icon? It's potentially a bit too detailed.

**Comment by JenMysoc** [comment]
OK, could you send me the mock up you did in Brighton then and I can send this over to them to approve?

**Comment by zarino** [comment]
Here's the one I showed you before:

![makemyisland-icon-1](https://cloud.githubusercontent.com/assets/739624/9087158/d8197604-3b80-11e5-9c25-2d7232869b4b.jpg)

As it happens, the full logo inside the icon doesn't look completely ridiculous:

![makemyisland-icon-2](https://cloud.githubusercontent.com/assets/739624/9087171/e427ea0c-3b80-11e5-8c74-cbc80e395dfd.jpg)

**Comment by JenMysoc** [comment]
Perfect I'll send this over for comments :)

**Comment by zarino** [comment]
> Perfect I'll send this over for comments :)

Yeah. To be honest, I'd be happy with them using either. Having the full logo in there might actually prove advantageous if it turns out that "MakeMyIsland" is too long a name to be displayed on an iPhone (and as such would be truncated to "Make…land" or similar.

**Comment by zarino** [comment]
> if it turns out that "MakeMyIsland" is too long a name to be displayed on an iPhone

Actually, I just tested it on my iPhone, and amazingly, it fits! So maybe we can use the full title for the app name.

**Comment by davea** [comment]
![ios simulator screen shot 5 aug 2015 14 53 57](https://cloud.githubusercontent.com/assets/4776/9087319/d3ca0e0a-3b81-11e5-9443-5f38381bdbe1.png)

I think we're OK with the app name - no truncation on iPhone 6 or 4S in the simulator.

_edit_: snap on the ice

**Comment by davea** [comment]
![screen shot 2015-08-05 at 10 46 04](https://cloud.githubusercontent.com/assets/4776/9090961/585738ce-3b95-11e5-9d14-2521e862b513.png)

Here's where we're up to with the main UI. Not entirely happy with the colours but it's getting there.

**Comment by JenMysoc** [comment]
Ok! @zarino We're happiest with the makemyisland logo that's on the website as the app logo as well! 

I see what you mean about the colours on the app @davea they almost clash with the map tiles :/

**Comment by zarino** [comment]
Image assets emailed to @davea.

@JenMysoc – I think the blue's ok.

**Comment by davea** [comment]
Sorry @zarino, I forgot the iPhone 6 Plus :disappointed: Can we please also have:
- Icon at 180x180 pixels
- Launch image at 1242x2208 pixels

**Comment by JenMysoc** [comment]
The video is cool!! it looks like it works nicely \o/ thanks @davea

**Comment by zarino** [comment]
@davea – I'll email the assets over to you, with the new iPhone 6 Plus additions.

Obviously the iOS icons get cropped into the iOS rounded squircle. But what about the Android icons? Do you need me to round them off?

**Comment by davea** [comment]
Good catch! I expect they'll need to be pre-rounded for Android, based on [the images we use](https://github.com/mysociety/fixmystreet-mobile/blob/makemyisland-rebrand/res/android/xhdpi.png) for the main FMS app.

**Comment by davea** [comment]
Yep, Android needs rounded icons:

![screen shot 2015-08-10 at 14 01 43](https://cloud.githubusercontent.com/assets/4776/9172046/60ff7faa-3f68-11e5-8d66-43bd694fb092.png)

Sadly, the app name _is_ wrapped on Android. Thoughts on what we should do here? Maybe 'MyIsland'?

**Comment by davea** [comment]
Or, given that Android will use up to two lines for app names, we could style it as 'Make My Island'?

**Comment by zarino** [comment]
"Make My Island" seems sensible.

**Comment by JenMysoc** [comment]
I agree. I think it's better to have the name with spaces rather than change the name which might confuse users a little :)

**Comment by davea** [comment]
![screen shot 2015-08-10 at 15 37 05](https://cloud.githubusercontent.com/assets/4776/9174042/b60abaca-3f75-11e5-9257-88ccf0903303.png)

That's better :)

**Comment by dracos** [comment]
As #19 was closed, I assume this is too ;)
