### ISSUE TITLE
Get device details from local team to test MakeMyIsland App

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#11]

**Comment by JenMysoc** [comment]
@davea we got this detail from our colleagues in the Maldives:

Latest versions of Android based phones (Samsung, LG, Sony etc) and iPhones are in use. Additionally ipads and android based tablets are in use.

Is that enough to test with?

**Comment by davea** [comment]
Ideally having the precise make & model of the test devices would be useful when we're collecting bug reports etc, but the provided info will be enough for now.

**Comment by JenMysoc** [comment]
@davea do we still need this?

**Comment by davea** [comment]
Nope!
