### ISSUE TITLE
Launch Maldives App on September 1st

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#19]
For both Android and Apple. Unless we hear different.

**Comment by davea** [comment]
:+1:

**Comment by davea** [comment]
Done!
- [iOS app store](https://itunes.apple.com/us/app/makemyisland/id1030462059?mt=8)
- [Android app store](https://play.google.com/store/apps/details?id=org.mysociety.MakeMyIsland)
