### ISSUE TITLE
Create bodies for new areas

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#2]
For the three areas in Greater Male' the reports will go to the Waste Authority

For the areas on the Fondahoo stretch reports will go to the Police Service and some relevant councils

Tasks:
We need to get the email addresses for these from the team on Fondahoo
We need to confirm which councils are accepting reports

**Comment by davea** [comment]
This is done on the staging site.

**Comment by dracos** [comment]
Two bodies on live, named "Fondahoo Island Council" and "Greater Male'" - should the latter be "Greater Male' Waste Authority"?

**Comment by JenMysoc** [comment]
The body should be named the Waste Authority
