### ISSUE TITLE
Set up basic version of FixMyStreet for Ghana

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#24]
- [x] English
- [x] Name: FixMyCommunity
- [x] Logo 
- [x] Start pilot in Central Region. http://www.openstreetmap.org/relation/3330281#map=9/5.6652/-1.2827 
- [x] Similar colours to FMS UK.
- [x] FAQ
- [x] Social media login
- [x] Social media sharing
- [x] A <a href="https://developers.facebook.com/docs/plugins/page-plugin">Facebook feed</a> from a central <a href="https://www.facebook.com/FixMyCommunity">Facebook page</a> on the homepage of the site

**Comment by dracos** [comment]
All done.
