### ISSUE TITLE
specific autolocate problems on Laamu Atoll on MakeMyIsland app

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet-international#25]
Works fine on other atolls, but not on Laamu.

Autolocate on the phone within the browser works fine there (although: I think the test that confirmed this was actually done on Fonadhoo (will check with Fizal of UNDP).

What's the difference in the mechanism used by autolate on the app vs. the browser?

**Comment by dracos** [comment]
Project gone.
