### ISSUE TITLE
[CM] Add french translation to the dansmonqwat.org site

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#39]
A new group is taking over DansMonQwat and relaunching it in November 2016 - they would like to have the site in both french and english as there are 2 regions that speak english and 8 that speak french in Cameroon.

There's already a french - france translation on transifex that is 96% complete and can be used as a base for the french addition.

This would include:
- [x] adding a language switcher to dansmonqwat.org
- [x] applying french translation to dansmonqwat.org

**Comment by dracos** [comment]
English and French both available on https://dansmonqwat.org , switcher currently top right.
