### ISSUE TITLE
Create or source administrative boundaries for new areas in MakeMyIsland

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#4]

**Comment by davea** [comment]
Two areas:
- Greater Male' covering:
  - Male'
  - Hulhamale'
  - Villimale'
- Fonadhoo Stretch covering:
  - Gan
  - Kahdhoo
  - Maandhoo
  - Fonadhoo

**Comment by davea** [comment]
Closing this in favour of #1.
