### ISSUE TITLE
[CM] Update the phone number on the homepage of dansmonqwat.org

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#40]
![screen shot 2016-08-18 at 15 23 01](https://cloud.githubusercontent.com/assets/4170351/17777550/dc8bc040-6558-11e6-84ba-5f100ee10439.png)

As Afroleadership take over the DansMonQwat platform they need to change the phone number on the homepage to +237 691 82 58 03

**Comment by dracos** [comment]
Updated to +237 671 05 05 71
