### ISSUE TITLE
[UG] Add total number of reports to FixMyCommunity homepage

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#43]
This can replace the updates on reports - or simply be added in to that selection of numbers about reports on the homepage

![screen shot 2016-09-09 at 10 12 37](https://cloud.githubusercontent.com/assets/4170351/18381833/0da32604-7676-11e6-8385-68245f2edd40.png)

**Comment by dracos** [comment]
This has been done.
