### ISSUE TITLE
[MV] Investigate why app and website are showing different maps for Hulhumale'

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#44]
The app and website show different maps. This is specific for Hulhumale’ (part of Greater Male’) The map on the website shows an extended second phase of the island and the app does not. 

![screen shot 2016-11-07 at 12 46 07](https://cloud.githubusercontent.com/assets/4170351/20058309/36a959f6-a4e8-11e6-8017-6de9277698d9.png)

**Comment by dracos** [comment]
Project gone.
