### ISSUE TITLE
Remove "mySociety will host for you" text from FMS.org

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#55]
There are at least three places where we suggest we'll host FMS sites for people fo free still and we're no longer offering that service. Please can we remove these mentions?

You can find them on 
https://fixmystreet.org/install/
![screen shot 2018-05-15 at 12 41 19](https://user-images.githubusercontent.com/4170351/40054706-b39dd522-583d-11e8-8a3a-910eec271fa0.png)

on https://fixmystreet.org/overview/
![screen shot 2018-05-15 at 12 40 50](https://user-images.githubusercontent.com/4170351/40054743-d41ce090-583d-11e8-819a-8f9fec658413.png)
This could probably be edited to suggest we might be able to put them in touch with someone who could help (eg CoCitizen)

and finally on in the expanding menu
https://fixmystreet.org/how-it-works/
![screen shot 2018-05-15 at 12 40 13](https://user-images.githubusercontent.com/4170351/40054813-02e3614c-583e-11e8-8692-bcb8b38eeb6d.png)

**Comment by dracos** [comment]
Also in checklist, bodies/contacts, promotion, surveys, admin training. All gone.
