### ISSUE TITLE
Get details of social media links for the website and app for MakeMyIsland

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#6]
@jenmysoc to do. including a social media log in

**Comment by davea** [comment]
This is on the report confirmation page as well as the report detail page now:
![screen shot 2015-08-07 at 16 16 20](https://cloud.githubusercontent.com/assets/4776/9139060/ad376a22-3d1f-11e5-8821-9715d082f979.png)

**Comment by JenMysoc** [comment]
They are as follows:

Gmail Login:
Username: makemyisland@gmail.com

Twitter Login:
Link: https://twitter.com/Makemyisland
Username: @MakemyIsland

Facebook:
Link: https://www.facebook.com/MakemyIsland

They can now be added to the site!
