### ISSUE TITLE
Identify text that needs updating or adding to MAkeMyIsland site and app

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#7]
For example; Help Pages and About pages

**Comment by davea** [comment]
Any updates on this yet?

**Comment by JenMysoc** [comment]
So I know the help and about pages but I don't know what other pages end up as non-generic pages. I haven't sent these over yet because I was hoping someone would let me know if there were any other pages! Sorry, I was a bit unclear!

**Comment by davea** [comment]
These are all (I think) the app templates that need text:
- https://github.com/mysociety/fixmystreet-mobile/blob/makemyisland-rebrand/www/templates/en/initial_help.html - shown upon first launch of the app
- https://github.com/mysociety/fixmystreet-mobile/blob/makemyisland-rebrand/www/templates/en/help.html - shown when clicking the '?' button, can probably use the same text as the site FAQ.
