### ISSUE TITLE
[Design] Define logo size we require for app and MakeMyIsland site

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#8]
- [ ] Check if the logo will be updated
- [ ] Get requirements from designers

**Comment by JenMysoc** [comment]
The logo will be updated for the application but not for the site; what requirements do we have for the site?

**Comment by davea** [comment]
The logo will need to be regenerated from a vector source for the site, as the current image looks jaggedy against the new background colour:

![screen shot 2015-07-30 at 16 12 16](https://cloud.githubusercontent.com/assets/4776/8986820/eb3b8380-36d5-11e5-9d1a-5b88376208a0.png)

**Comment by JenMysoc** [comment]
Ok sure, what does this mean? Do I need to request a new version from the team?

**Comment by davea** [comment]
I think we'll be able to handle this internally, but @zarino and/or @wrightmartin would know for sure.

**Comment by zarino** [comment]
@JenMysoc @davea: I have a high-res version of the logo now.
